klabban/web/forms/refugees.py
from flask_wtf import FlaskForm
from flask_mongoengine.wtf import model_form
from klabban.web import models
from wtforms import StringField, SelectField

BaseRefugeeForm = model_form(
    models.Refugee,
    FlaskForm,
    field_args={
        "refugee_camp": {"label": "ศูนย์พักพิง", "label_attr": "name"},
        "nick_name": {"label": "ชื่อเล่น"},
        "name": {"label": "ชื่อ-นามสกุล"},
        "nationality": {"label": "สัญชาติ", "default": "ไทย"},
        "ethnicity": {"label": "เชื้อชาติ", "default": "ไทย"},
        "remark": {"label": "หมายเหตุ"},
        "status": {"label": "สถานะ"},
    },
)


class RefugeeForm(BaseRefugeeForm):
    pass


class RefugeeSearchForm(FlaskForm):
    search = StringField("ค้นหา", render_kw={"placeholder": "ค้นหาชื่อผู้อพยพ"})
    refugee_camp = SelectField("ศูนย์พักพิง")

klabban/web/views/refugees.py
from flask import abort, Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from ..utils.acl import roles_required
from klabban import models
from klabban.web import forms
from mongoengine.queryset.visitor import Q
from uuid import uuid4
from flask_mongoengine import Pagination


module = Blueprint("refugees", __name__, url_prefix="/refugees")


@module.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    per_page = 50  # จำนวนรายการต่อหน้า

    search_form = forms.refugees.RefugeeSearchForm(request.args)
    search_form.refugee_camp.choices = [("", "ทั้งหมด")] + [
        (str(camp.id), camp.name)
        for camp in models.RefugeeCamp.objects(status__ne="deactive").order_by("name")
    ]
    search = search_form.search.data
    refugee_camp_id = search_form.refugee_camp.data

    query = models.Refugee.objects(status__ne="deactive").order_by("name")
    
    if search:
        query = query.filter(
            Q(name__icontains=search) | Q(nick_name__icontains=search)
        )
    if refugee_camp_id:
        query = query.filter(refugee_camp=refugee_camp_id)
    try:
        refugees_pagination = Pagination(query, page=page, per_page=per_page)
    except ValueError:
        refugees_pagination = Pagination(query, page=1, per_page=per_page)

    return render_template(
        "/refugees/index.html", 
        refugees_pagination=refugees_pagination,
        search_form=search_form,
    )


@module.route("/create", methods=["GET", "POST"], defaults={"refugee_id": None})
@module.route("/<refugee_id>/edit", methods=["GET", "POST"])
@roles_required(["admin", "refugee_camp_staff"])
def create_or_edit(refugee_id):
    form = forms.refugees.RefugeeForm()
    refugee = models.Refugee()

    if "admin" in current_user.roles:
        form.refugee_camp.choices = [
            (str(camp.id), camp.name)
            for camp in models.RefugeeCamp.objects(status__ne="deactive").order_by(
                "name"
            )
        ]
    elif "refugee_camp_staff" in current_user.roles:
        form.refugee_camp.choices = [
            (str(current_user.refugee_camp.id), current_user.refugee_camp.name)
        ]
        form.refugee_camp.data = str(current_user.refugee_camp.id)
    else:
        form.refugee_camp.choices = []

    if refugee_id:
        refugee = models.Refugee.objects.get(id=refugee_id)
        form = forms.refugees.RefugeeForm(obj=refugee)
    # else:
    #   refugee.created_by = current_user._get_current_object()

    if request.method == "GET":
        return render_template(
            "refugees/create_or_edit.html",
            form=form,
            refugee_id=refugee_id,
        )

    if not form.validate_on_submit():
        return redirect(
            url_for(
                "refugees.index",
                **request.args,
            )
        )

    form.populate_obj(refugee)
    # refugee.updated_by = current_user._get_current_object()
    refugee.save()

    return redirect(url_for("refugees.index"))


@module.route("/delete/<refugee_id>", methods=["POST"])
@roles_required(["admin", "refugee_camp_staff"])
def delete_refugee(refugee_id):
    refugee = models.Refugee.objects(id=refugee_id).first()
    if (
        "admin" not in current_user.roles
        and refugee.refugee_camp.id != current_user.refugee_camp.id
    ):
        return abort(403)
    if refugee:
        refugee.status = "deactive"
        refugee.save()
    return redirect(url_for("refugees.index"))

klabban/web/templates/refugees/create_or_edit.html
{% extends "/base/default_page.html" %}
{% import "base/html_renderer.html" as renderer %}

{% set title_page="จัดการผู้อพยพ" %}

{% block content %}
<form class="bg-white rounded-lg p-4" method="post" action="{{ url_for('refugees.create_or_edit', refugee_id=refugee_id) }}">
    {{ form.csrf_token }}
    {{ renderer.base_render(form.refugee_camp) }}
    <div class="grid grid-cols-2 gap-x-4">
        {{ renderer.base_render(form.nick_name) }}
        {{ renderer.base_render(form.name) }}
        {{ renderer.base_render(form.nationality) }}
        {{ renderer.base_render(form.ethnicity) }}
    </div>
    {{ renderer.render_text_area_field(form.remark) }}
    {{ renderer.base_render(form.status) }}
    <div class="modal-action justify-end">
        <a class="btn" href="{{ url_for('refugees.index') }}">
            ปิด
        </a>
        <button class="btn btn-primary">
            ยืนยัน
        </button>
    </div>
</form>
{% endblock %}

klabban/web/templates/refugees/index.html
{% extends "/base/default_page.html" %}
{% import "base/html_renderer.html" as renderer %}
{% import "/components/dialogs.html" as dialog %}
{% import "/components/paginations.html" as paginations %}

{% set title_page="รายชื่อผู้อพยพ" %}

{% block content %}
<div class="bg-white rounded-3xl border border-gray-300">
    <div class="overflow-x-auto p-6">
        <div class="flex flex-row items-end justify-between mb-2">
            <form method="GET">
                <div class="text-xl font-medium text-gray-700">
                    ค้นหารายชื่อผู้อพยพ
                </div>
                <div class="flex gap-4 items-center">
                    {{ renderer.base_render(search_form.refugee_camp) }}
                    {{ renderer.base_render(search_form.search) }}
                    <button type="submit" class="btn btn-primary text-white mt-4">
                        ค้นหา
                    </button>
                </div>
            </form>
            {% if 'admin' in current_user.roles or 'refugee_camp_staff' in current_user.roles %}
                <a class="btn btn-primary text-white" href="{{ url_for('refugees.create_or_edit', **request.args) }}">
                    <span class="material-symbols-outlined text-sm">add</span>
                    เพิ่มผู้อพยพ
                </a>
            {% endif %}
        </div>
        <table class="table  w-full text-sm border-x border-t border-gray-200 ">
            <thead class=" text-gray-700">
                <tr>
                <th>ลำดับ</th>
                <th>ชื่อเล่น</th>
                <th>ชื่อ-นามสกุล</th>
                <th>สถานะ</th>
                <th>ศูนย์พักพิง</th>
                <th></th>
                </tr>
            </thead>
            <tbody>
                {% for refugee in refugees_pagination.items %}
                <tr class="border-b border-x border-gray-200">
                    <td>{{ loop.index }}</td>
                    <td>{{ refugee.nick_name }}</td>
                    <td>{{ refugee.name }}</td>
                    <td>
                        <div class="border rounded-lg py-1 px-2 size-fit
                            {{ 'text-blue-500 border-blue-500' if refugee.status == 'active' else '' }}
                            {{ 'text-red-500 border-red-500' if refugee.status == 'deactive' else '' }}
                            {{ 'text-green-500 border-green-500' if refugee.status == 'back_home' else '' }}
                             ">
                             {{ refugee.get_status_display() }}
                        </div>
                    </td>
                    <td>{{ refugee.refugee_camp.name }}</td>
                    <td class="flex gap-2 justify-end">
                        <a href="{{ url_for('refugees.create_or_edit', refugee_id=refugee.id) }}" class="btn btn-outline btn-sm text-gray-600 border-gray-300">
                            <span class="material-symbols-outlined">
                                edit_square
                            </span>
                        </a>
                        <button class="btn btn-outline btn-sm border-gray-300 text-error"
                           onclick="$('#{{refugee.id}}-disactive-dialog')[0].showModal()">
                            <span class="material-symbols-outlined">
                            delete
                            </span>
                        </button>
                        {{ dialog.DisactiveDialog(
                            id="%s-disactive-dialog" | format(refugee.id),
                            title="ยืนยันการลบรายการผู้อพยพ",
                            body="คุณต้องการที่จะลบรายการผู้อพยพชื่อ <b>%s</b> ใช่หรือไม่?" | format(refugee.name),
                            url=url_for("refugees.delete_refugee", refugee_id=refugee.id)
                        )}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {{ paginations.render_pagination(
            pagination=refugees_pagination,
            endpoint='refugees.index',
            key_page='page',
            kwargs=request.args.to_dict()
        ) }}
    </div>
</div>
{% endblock %}