klabban/web/forms/refugee_camps.py
from flask_wtf import FlaskForm
from flask_mongoengine.wtf import model_form
from klabban.web import models

BaseRefugeeCampForm = model_form(
    models.RefugeeCamp,
    FlaskForm,
    field_args={
        "name": {"label": "ชื่อศูนย์พักพิง"},
        "location_url": {"label": "ลิงก์ที่ตั้ง (Google Maps)"},
        "contact_info": {"label": "ข้อมูลติดต่อ"},
        "line_id": {"label": "Line ID"},
        "other_link": {"label": "ลิงก์อื่น ๆ"},
        "description": {"label": "รายละเอียด"},
    },
)


class RefugeeCampForm(BaseRefugeeCampForm):
    pass

klabban/web/views/refugee_camps.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user

from klabban import models
from klabban.web import forms
from mongoengine.queryset.visitor import Q
from uuid import uuid4

import pandas as pd
import datetime

module = Blueprint("refugee_camps", __name__, url_prefix="/refugee_camps")


@module.route("/")
def index():
    refugee_camps = models.RefugeeCamp.objects(status="active").order_by("name" )
    return render_template("/refugee_camps/index.html", refugee_camps=refugee_camps)

@module.route(
    "/create", methods=["GET", "POST"], defaults={"refugee_camp_id": None}
)
@module.route("/<refugee_camp_id>/edit", methods=["GET", "POST"])
# @login_required
def create_or_edit_refugee_camp(refugee_camp_id):
    form = forms.refugee_camps.RefugeeCampForm()
    refugee_camp = models.RefugeeCamp()
    modal_id = uuid4()

    if refugee_camp_id:
        refugee_camp = models.RefugeeCamp.objects.get(id=refugee_camp_id)
        form = forms.refugee_camps.RefugeeCampForm(obj=refugee_camp)
    # else:
    #   refugee_camp.created_by = current_user._get_current_object()

    if request.method == "GET":

        return render_template(
            "/components/refugee_camps/create_or_edit_modal.html",
            form=form,
            modal_id=modal_id,
            refugee_camp_id=refugee_camp_id,
        )

    if not form.validate_on_submit():
        return redirect(
            url_for(
                "refugee_camps.index",
                **request.args,
            )
        )

    form.populate_obj(refugee_camp)
    # refugee_camp.updated_by = current_user._get_current_object()
    refugee_camp.save()

    return redirect(url_for("refugee_camps.index"))



@module.route("/delete/<refugee_camp_id>", methods=["POST"])
# @login_required
def delete_refugee_camp(refugee_camp_id):
    refugee_camp = models.RefugeeCamp.objects(id=refugee_camp_id).first()
    if refugee_camp:
        refugee_camp.status = "deactive"
        refugee_camp.save()
    return redirect(
        url_for("refugee_camps.index")
    )

klabban/web/templates/refugee_camps/create_or_edit.html
{% extends "/base/default_page.html" %}
{% import "/components/dialogs.html" as dialog %}
{% set title_page="จัดการศูนย์พักพิง" %}

{% block content %}
<div id="create_or_edit_refugee_camp-modal"></div>
<div class="bg-white rounded-3xl border border-gray-300">
    <div class="overflow-x-auto p-6">
        <div class="flex flex-row items-center justify-between mb-2">
            <span class="text-xl font-medium text-gray-700">
                ศูนย์พักพิง
            </span>
            <button class="btn btn-success btn-sm text-white" 
            hx-target="#create_or_edit_refugee_camp-modal" 
            hx-get="{{ url_for('refugee_camps.create_or_edit_refugee_camp', **request.args) }}">
                <span class="material-symbols-outlined text-sm">add</span>
                เพิ่มศูนย์พักพิง
            </button>
        </div>
        <table class="table  w-full text-sm border-x border-t border-gray-200 ">
            <thead class=" text-gray-700">
                <tr>
                <th>ลำดับ</th>
                <th>ชื่อศูนย์พักพิง</th>
                <th>ตำแหน่ง</th>
                <th class="text-center">จัดการ</th>
                </tr>
            </thead>
            <tbody>
                {% for refugee_camp in refugee_camps %}
                <tr class="border-b border-x border-gray-200">
                    <td>{{ loop.index }}</td>
                    <td>{{ refugee_camp.name }}</td>
                    <td>{{ refugee_camp.location_url }}</td>
                  
                    <td class="flex gap-2 justify-center">
                        <button
                        hx-target="#create_or_edit_refugee_camp-modal" 
                        hx-get="{{ url_for('refugee_camps.create_or_edit_refugee_camp',refugee_camp_id=refugee_camp.id, **request.args) }}"
                        class="btn btn-outline btn-sm text-gray-600 border-gray-300">
                            <span class="material-symbols-outlined">
                                edit_square
                            </span>
                        </button>
                        <button class="btn btn-outline btn-sm border-gray-300 text-error"
                           onclick="$('#{{refugee_camp.id}}-disactive-dialog')[0].showModal()">
                            <span class="material-symbols-outlined">
                            delete
                            </span>
                        </button>
                        {{ dialog.DisactiveDialog(
                        id="%s-disactive-dialog" | format(refugee_camp.id),
                        title="ยืนยันการลบรายการศูนย์พักพิง",
                        body="คุณต้องการที่จะลบรายการศูนย์พักพิงชื่อ <b>%s</b> ใช่หรือไม่?" | format(refugee_camp.name),
                        url=url_for("refugee_camps.delete_refugee_camp",
                        refugee_camp_id=refugee_camp.id)
                        )}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

klabban/web/templates/refugee_camps/index.html
{% extends "/base/default_page.html" %}
{% import "/components/dialogs.html" as dialog %}
{% set title_page="จัดการศูนย์พักพิง" %}

{% block content %}
<div id="create_or_edit_refugee_camp-modal"></div>
<div class="bg-white rounded-3xl border border-gray-300">
    <div class="overflow-x-auto p-6">
        <div class="flex flex-row items-center justify-between mb-2">
            <span class="text-xl font-medium text-gray-700">
                ศูนย์พักพิง
            </span>
            <button class="btn btn-success btn-sm text-white" 
            hx-target="#create_or_edit_refugee_camp-modal" 
            hx-get="{{ url_for('refugee_camps.create_or_edit_refugee_camp', **request.args) }}">
                <span class="material-symbols-outlined text-sm">add</span>
                เพิ่มศูนย์พักพิง
            </button>
        </div>
        <table class="table  w-full text-sm border-x border-t border-gray-200 ">
            <thead class=" text-gray-700">
                <tr>
                <th>ลำดับ</th>
                <th>ชื่อศูนย์พักพิง</th>
                <th>ตำแหน่ง</th>
                <th class="text-center">จัดการ</th>
                </tr>
            </thead>
            <tbody>
                {% for refugee_camp in refugee_camps %}
                <tr class="border-b border-x border-gray-200">
                    <td>{{ loop.index }}</td>
                    <td>{{ refugee_camp.name }}</td>
                    <td>
                        {% if refugee_camp.location_url %}
                        <a href="{{ refugee_camp.location_url }}" target="_blank" class="text-blue-600 hover:underline">
                        คลิกดูตำแหน่ง
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td class="flex gap-2 justify-center">
                        <button
                        hx-target="#create_or_edit_refugee_camp-modal" 
                        hx-get="{{ url_for('refugee_camps.create_or_edit_refugee_camp',refugee_camp_id=refugee_camp.id, **request.args) }}"
                        class="btn btn-outline btn-sm text-gray-600 border-gray-300">
                            <span class="material-symbols-outlined">
                                edit_square
                            </span>
                        </button>
                        <button class="btn btn-outline btn-sm border-gray-300 text-error"
                           onclick="$('#{{refugee_camp.id}}-disactive-dialog')[0].showModal()">
                            <span class="material-symbols-outlined">
                            delete
                            </span>
                        </button>
                        {{ dialog.DisactiveDialog(
                        id="%s-disactive-dialog" | format(refugee_camp.id),
                        title="ยืนยันการลบรายการศูนย์พักพิง",
                        body="คุณต้องการที่จะลบรายการศูนย์พักพิงชื่อ <b>%s</b> ใช่หรือไม่?" | format(refugee_camp.name),
                        url=url_for("refugee_camps.delete_refugee_camp",
                        refugee_camp_id=refugee_camp.id)
                        )}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}