klabban/web/views/accounts.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    request,
    session,
    redirect,
    Response,
    send_file,
    flash,
)
from flask_login import login_required, current_user, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
import datetime

from .. import oauth2
from .. import forms
from klabban.web import models

module = Blueprint("accounts", __name__)


@module.route("/login", methods=["GET", "POST"])
def login():
    form = forms.accounts.LoginForm()
    if not form.validate_on_submit():
        error_msg = form.errors
        if form.errors == {"password": ["Field must be at least 6 characters long."]}:
            error_msg = "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง"
        if form.errors == {"password": ["This field is required."]}:
            error_msg = "กรุณากรอกรหัสผ่าน"

        return render_template("/accounts/login.html", form=form, error_msg=error_msg)

    user = models.User.objects(username=form.username.data).first()
    if not user or not user.check_password(form.password.data):
        error_msg = "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง"
        return render_template("/accounts/login.html", form=form, error_msg=error_msg)

    if user.status == "disactive":
        error_msg = "บัญชีของท่านถูกลบออกจากระบบ"
        return render_template("/accounts/login.html", form=form, error_msg=error_msg)

    login_user(user)
    user.last_login_date = datetime.datetime.now()
    user.save()
    next = request.args.get("next")
    if next:
        return redirect(next)

    return redirect(url_for("index.index"))


@module.route("/login/<name>")
def login_oauth(name):
    client = oauth2.oauth2_client

    scheme = request.environ.get("HTTP_X_FORWARDED_PROTO", "http")

    redirect_uri = url_for(
        "accounts.authorized_oauth", name=name, _external=True, _scheme=scheme
    )
    response = None
    if name == "google":
        response = client.google.authorize_redirect(redirect_uri)
    elif name == "facebook":
        response = client.facebook.authorize_redirect(redirect_uri)
    elif name == "line":
        response = client.line.authorize_redirect(redirect_uri)

    elif name == "psu":
        response = client.psu.authorize_redirect(redirect_uri)
    elif name == "engpsu":
        response = client.engpsu.authorize_redirect(redirect_uri)
    return response


@module.route("/auth/<name>")
def authorized_oauth(name):
    client = oauth2.oauth2_client
    remote = None
    try:
        if name == "google":
            remote = client.google
        elif name == "facebook":
            remote = client.facebook
        elif name == "line":
            remote = client.line
        elif name == "psu":
            remote = client.psu
        elif name == "engpsu":
            remote = client.engpsu

        token = remote.authorize_access_token()

    except Exception as e:
        print("autorize access error =>", e)
        return redirect(url_for("accounts.login"))

    session["oauth_provider"] = name
    return oauth2.handle_authorized_oauth2(remote, token)


@module.route("/logout", methods=["POST", "GET"])
@login_required
def logout():
    logout_user()
    return redirect("/")

klabban/web/views/index.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required
import datetime
from klabban import models

module = Blueprint("index", __name__)


@module.route("/")
def index():
    refugee_camps = models.RefugeeCamp.objects(status="active").order_by("created_at")
    return render_template("index/index.html", refugee_camps=refugee_camps)

klabban/web/templates/base/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
      {{ config.APP_TITLE }}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ 'css/app.css' | static_url }}">
    <script src="{{ 'node_modules/jquery/dist/jquery.min.js' | static_url }}"></script>
    <script type="module" src="{{ 'node_modules/cally/dist/cally.js' | static_url }}"></script>
    <script src="{{ 'node_modules/htmx.org/dist/htmx.min.js' | static_url }}"></script>
    <link rel="stylesheet" type="text/css"
      href="{{ 'node_modules/@phosphor-icons/web/src/regular/style.css' | static_url }}">
    <link rel="stylesheet" type="text/css"
      href="{{ 'node_modules/@phosphor-icons/web/src/fill/style.css' | static_url }}">
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0..1,0" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.18/index.global.min.js"></script>
    {% block head %}
    {% endblock head %}
  </head>

  <body>
    {% block body %}
    {% endblock %}

    {% block js %}
    {% endblock js %}
  </body>

</html>

klabban/web/templates/base/default_page.html
{% extends "base/base.html" %}

{% block body %}
<div class="drawer 2xl:drawer-open">
  <div id="change-password-modal"></div>
  <input id="drawer-menu" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content bg-base-100">
    <div
      class="drawer-content {{ 'flex flex-row  border-b border-transparent shadow-md' if current_user.is_authenticated else '' }} ">
      {% if current_user.is_authenticated %}
      <label for="drawer-menu" class="drawer-button btn btn-outline ml-4 mt-4  2xl:hidden
            h-11 w-11 p-0 flex items-center justify-center
            rounded-xl border-gray-300
            hover:bg-gray-100 hover:border-gray-400
            active:scale-95 transition-all duration-200">
        <span class="material-symbols-outlined text-2xl text-gray-700">
          menu
        </span>

      </label>
      {% endif %}
      <div
        class="navbar bg-base-100 {{ 'border-b border-transparent shadow-md px-4 py-6' if not current_user.is_authenticated else '' }} max-sm:flex-col max-sm: justify-center">
        <div class="navbar-start max-sm:justify-center">
          {#
          <img src="/static/images/logo/psu_square.png" alt="diisLogio" class="h-10 w-10 mr-2 aspect-auto" />
          <img src="/static/images/logo/coe_psu.jpg" alt="diisLogio" class="h-10 w-10 mr-2" />
          <img src="/static/images/logo/r202.png" alt="diisLogio" class="h-10 w-10 mr-2" />
          <img src="/static/images/logo/import_star.png" alt="diisLogio" class="h-10 w-10 mr-2" />
          #}
        </div>
        <div class="navbar-end gap-3 max-sm:justify-center max-sm:mt-2">
          {% if not current_user.is_authenticated %}
          <a class="btn btn-primary rounded-full px-6 font-normal"
            href="{{ url_for('accounts.login') }}">เข้าสู่ระบบ</a>
          <a class="btn btn-primary btn-outline rounded-full px-6 font-normal"
            href="{{ url_for('accounts.login') }}">สำหรับเจ้าหน้าที่</a>
          {% else %}
          <a href="{{ url_for('accounts.logout') }}"
            class="btn btn-primary btn-outline rounded-full px-6 font-normal">ออกจากระบบ</a>
          {% endif %}
        </div>
      </div>
    </div>


    <div class="flex flex-col h-fit">
      <div class="pt-4 px-4">
        {% block back_button %}
        {% endblock back_button %}
      </div>
      <div class="w-full  p-4">
        <div class="w-full flex flex-row">
          <span class="text-xl font-bold">
            {{ title_page }}
          </span>
        </div>
        <div class="w-full">
          <span class="text-sm text-base-content/60">
            {{ description_page }}
          </span>
        </div>
      </div>
      <div class="lg:px-2 mx-2 pb-5 min-h-screen">
        {% block content %}
        {% endblock content %}
      </div>
      {% include "base/footer.html" %}
    </div>
  </div>
  {% include "base/sidebar.html" %}
</div>
{% endblock body %}

klabban/web/templates/base/error.html
{% extends "base/base.html" %}

{% block body %}
<div class="flex w-full h-screen justify-center items-center">
  <p class="text-error text-3xl">
    {{ error_msg }}
  </p>
</div>
{% endblock %}

klabban/web/templates/base/footer.html
<div class="p-8 w-full bg-primary text-white">
  <div class="w-full md:w-3xl lg:w-5xl mx-auto">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <div class="min-h-[20vh] flex flex-col gap-4">
        <h5 class="text-lg md:text-base lg:text-lg font-semibold">Hakon web</h5>

        <div class="flex flex-row items-center gap-6">
          <img src="{{ url_for('static', filename='images/logo/psu-logo.png') }}"
                alt="PSU logo" class="h-20 md:h-24 w-auto object-contain" />
          <img src="{{ url_for('static', filename='images/logo/diis-logo.png') }}"
               alt="DIIS logo" class="h-16 md:h-16 w-auto object-contain" />
        </div>

        <div class="flex items-center gap-2 mt-2">
          <img src="{{ url_for('static', filename='images/logo/coe_psu.jpg') }}"
               alt="COE PSU" class="h-10 w-auto mr-2" />
          <img src="{{ url_for('static', filename='images/logo/r202.png') }}"
               alt="R202" class="h-10 w-auto mr-2" />
          <img src="{{ url_for('static', filename='images/logo/import_star.png') }}"
               alt="Import Star" class="h-10 w-auto mr-2" />
        </div>

        <p class="text-sm md:text-base">Develop by R202 and Import Star Co.</p>
      </div>

      <div class="flex flex-col gap-4">
        <p class="text-sm md:text-base lg:text-lg">Prince of Songkla university<br />Hat Yai, Thailand</p>
      </div>

      <div class="flex flex-col gap-4">
        <h5 class="text-base md:text-base lg:text-lg ">Connect</h5>
        <a href="https://diis.psu.ac.th"
           class="text-sm md:text-base hover:underline">DIIS</a>
      </div>

    </div>
  </div>
</div>

klabban/web/templates/base/sidebar.html
<div class="drawer-side shadow {{ 'hidden' if not current_user.is_authenticated else '' }} ">
  <label for="drawer-menu" aria-label="close sidebar" class="drawer-overlay h-full"></label>

  <div class="flex flex-col h-full bg-gradient-to-b from-blue-600 to-primary text-white w-64">

    <!-- Header -->
    <div class="px-8 py-5 flex items-center justify-between border-b border-blue-400/30">
      <div class="flex items-center gap-3">
        <div class="p-2 rounded-xl">
          <i class="ph ph-user-check text-2xl"></i>
        </div>
        <div>
          <div class="text-xl font-bold">
            หาคน
          </div>
        </div>
      </div>
    </div>


    <!-- Menu -->
    <div class="flex-grow text-sm menu w-full">
      <ul class="menu gap-2 w-full">

        <li>
          <a class="{{ 'drawer-menu-active' if request.path == url_for('index.index') else '' }}"
            href="{{ url_for('index.index') }}">
            <i class="ph ph-layout-grid text-lg"></i>
            แดชบอร์ด
          </a>
        </li>
        {% if "admin" in current_user.roles %}
        <li>
          <a class="{{ 'drawer-menu-active' if '/refugee_camps' in request.path else '' }}"
            href="{{ url_for('refugee_camps.index') }}">
            <i class="ph ph-house-line text-lg"></i>
            ศูนย์พักพิง
          </a>
        </li>
        {% endif %}
        <li class="">
          <a class="{{ 'drawer-menu-active' if '/refugees' in request.path else '' }}"
            href="{{ url_for('refugees.index') }}">
            <i class="ph ph-person text-lg"></i>
            ผู้อพยพ
          </a>
        </li>
        {% if "admin" in current_user.roles %}
          <li>
            <a class="{{ 'drawer-menu-active' if '/users' in request.path else '' }}"
              href="{{ url_for('users.index') }}">
              <i class="ph ph-users text-lg"></i>
              ผู้ใช้งาน
            </a>
          </li>
        {% endif %}
      </ul>
      <ul class="mt-auto menu gap-2 w-full">
        {% if current_user.is_authenticated %}
          <li>
            <a class="text-red-500" href="{{ url_for('accounts.logout') }}">
              <i class="ph ph-sign-out text-lg"></i>
              ออกจากระบบ
            </a>
          </li>
        {% else %}
          <li>
            <a class="text-white" href="{{ url_for('accounts.login') }}">
              <i class="ph ph-sign-in text-lg"></i>
              เข้าสู่ระบบ
            </a>
          </li>
        {% endif %}
      </ul>
  </div>
</div>